#!/bin/bash

echo "🔥 Android生日提醒应用编译指南"
echo "================================"
echo ""
echo "📋 编译步骤："
echo ""
echo "1️⃣  生成调试版APK："
echo "   ./gradlew assembleDebug"
echo ""
echo "2️⃣  生成发布版APK："
echo "   ./gradlew assembleRelease"
echo ""
echo "3️⃣  清理项目："
echo "   ./gradlew clean"
echo ""
echo "4️⃣  编译并直接安装到设备："
echo "   ./gradlew installDebug"
echo ""
echo "📱 安装到手机："
echo ""
echo "1️⃣  通过USB连接手机并开启USB调试"
echo ""
echo "2️⃣  安装APK到手机："
echo "   adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "3️⃣  卸载应用："
echo "   adb uninstall com.birthday.reminder"
echo ""
echo "📁 生成的APK文件位置："
echo "   调试版：app/build/outputs/apk/debug/app-debug.apk"
echo "   发布版：app/build/outputs/apk/release/app-release.apk"
echo ""
echo "🔧 常用命令："
echo ""
echo "   查看连接的设备："
echo "   adb devices"
echo ""
echo "   查看应用日志："
echo "   adb logcat | grep BirthdayReminder"
echo ""
echo "   启动应用："
echo "   adb shell am start -n com.birthday.reminder/.MainActivity"
echo ""
